### PR TITLE
Simplified print functions

### PR DESCRIPTION
**Pull request by niansa**

### CODE REVIEW

**Comment by ADBeta** [comment]
I don't like this method of printing a \0 terminated string, but will change println to leverage print

**Comment by niansa** [comment]
> I don't like this method of printing a \0 terminated string, but will change println to leverage print

Why? It's way faster than iterating once (inside `strlen`) and then again to print everything. In fact, iterating until a number reaches zero and incrementing a pointer each time is quite a bit slower than just incrementing the pointer until it points to zero.

Edit: And yes the current behavior also requires more flash storage which is something that can become quite scarce in bigger projects. Wasting it on code style opinions may not be the best idea.

**Comment by ADBeta** [comment]
I don't mean the concept is bad, I just don't like your execution, with the for loop, and testing against literal 0. 
I changed the code to look like this 
```c
while(*string != '\0')
{
	// Wait for the current transmission to finish
	while(!(USART1->STATR & USART_FLAG_TC));
	USART1->DATAR = *string++;
}
```

Code style is just as important as code size. All well and good having a Ferrari, but no good if the steering wheel works in 4 dimensions :)

**Comment by niansa** [comment]
That looks good. Not my style but if you like it that way why not.

**Pull request closed without merging**
